"""
Cleanup orphaned thumbnail files from the thumbnails volume.

A thumbnail is considered orphaned when its UUID filename does not match
any photo record in the database.  This happens when thumbnails were
generated by a different compose project (docker-*) whose database is
separate from the current one (photosapp-*), or after photos are deleted.

Usage (inside the backend container or with PYTHONPATH set):

    # Dry-run — prints what would be deleted, touches nothing
    python scripts/cleanup_thumbnails.py

    # Actually delete orphaned files
    python scripts/cleanup_thumbnails.py --delete

    # Scope to a single size directory
    python scripts/cleanup_thumbnails.py --sizes sm lg

Run from the project root:
    docker exec photosapp-backend-1 python /app/scripts/cleanup_thumbnails.py
    docker exec photosapp-backend-1 python /app/scripts/cleanup_thumbnails.py --delete
"""
import argparse
import os
import sys

# Allow running both inside the container and from the host with PYTHONPATH
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))


def main():
    parser = argparse.ArgumentParser(description="Clean up orphaned thumbnail files")
    parser.add_argument(
        "--delete",
        action="store_true",
        default=False,
        help="Actually delete orphaned files (default: dry-run only)",
    )
    parser.add_argument(
        "--sizes",
        nargs="+",
        choices=["sm", "md", "lg"],
        default=["sm", "md", "lg"],
        help="Which size directories to process (default: all)",
    )
    args = parser.parse_args()

    from app.config import get_settings
    from app.core.database import get_sync_db
    from app.models.photo import Photo
    from sqlalchemy import select

    settings = get_settings()
    thumbnails_dir = settings.thumbnails_dir

    if args.delete:
        print("MODE: DELETE — orphaned files will be removed")
    else:
        print("MODE: DRY-RUN — no files will be deleted (pass --delete to remove)")

    print(f"Thumbnails directory: {thumbnails_dir}\n")

    # Load all valid photo UUIDs from DB into a set for O(1) lookup
    db = get_sync_db()
    try:
        valid_uuids = set(
            str(r[0]) for r in db.execute(select(Photo.id)).fetchall()
        )
    finally:
        db.close()

    print(f"Valid photo UUIDs in DB: {len(valid_uuids):,}\n")

    grand_total = grand_orphaned = grand_bytes = 0

    for size in args.sizes:
        size_dir = os.path.join(thumbnails_dir, size)
        if not os.path.isdir(size_dir):
            print(f"[{size}] Directory not found, skipping: {size_dir}")
            continue

        files = sorted(os.listdir(size_dir))
        total = len(files)
        orphaned_count = orphaned_bytes = skipped = 0

        for fname in files:
            # Skip macOS resource-fork / hidden files (._xxx, .DS_Store, etc.)
            if fname.startswith("."):
                skipped += 1
                continue

            stem = os.path.splitext(fname)[0]
            if stem in valid_uuids:
                continue

            fpath = os.path.join(size_dir, fname)
            try:
                fsize = os.path.getsize(fpath)
            except OSError:
                fsize = 0

            orphaned_count += 1
            orphaned_bytes += fsize

            if args.delete:
                try:
                    os.remove(fpath)
                except OSError as e:
                    print(f"  ERROR deleting {fpath}: {e}")

        valid_count = total - orphaned_count - skipped
        print(
            f"[{size}] {total:>7,} files  |  "
            f"{valid_count:>7,} valid  |  "
            f"{skipped:>5,} dotfiles skipped  |  "
            f"{orphaned_count:>7,} orphaned  ({orphaned_bytes / 1024 / 1024:.1f} MB)"
            + ("  → deleted" if args.delete else "  → would delete")
        )

        grand_total += total
        grand_orphaned += orphaned_count
        grand_bytes += orphaned_bytes

    print(
        f"\nTOTAL: {grand_total:,} files, {grand_orphaned:,} orphaned "
        f"({grand_bytes / 1024 / 1024:.1f} MB / {grand_bytes / 1024 / 1024 / 1024:.2f} GB)"
    )
    if not args.delete and grand_orphaned:
        print("\nRun with --delete to remove orphaned files.")


if __name__ == "__main__":
    main()
